"""add book_id to mybook model

Revision ID: 1295827440de
Revises: 5504d72a59bd
Create Date: 2023-08-04 09:14:31.140467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1295827440de'
down_revision = '5504d72a59bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_my_books_book_id_books'), 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_my_books_book_id_books'), type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###
