"""create book model

Revision ID: 159a024e4499
Revises: f0151b135b39
Create Date: 2023-08-02 17:07:59.137119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159a024e4499'
down_revision = 'f0151b135b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
