"""add author info to book model

Revision ID: 66f802283fa5
Revises: 159a024e4499
Create Date: 2023-08-03 13:24:32.114142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f802283fa5'
down_revision = '159a024e4499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('author_last_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('author_last_name')
        batch_op.drop_column('author_first_name')

    # ### end Alembic commands ###
