"""add mybook model

Revision ID: fd8e9fa4b331
Revises: 2d8a2ece8b10
Create Date: 2023-08-04 09:10:21.437022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8e9fa4b331'
down_revision = '2d8a2ece8b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_my_books'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_books')
    # ### end Alembic commands ###
